import { client } from "../../seacretDirectory/seacret";

import type {
  InferGetStaticPropsType,
  GetStaticPropsContext,
  NextPage,
} from "next";
import type { Contents, Blog, Tags } from "../../types/blog";

import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Card from "../../components/Card";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export const getStaticPaths = async () => {
  const data = await client.get({ endpoint: "tags" });

  const paths = data.contents.map(
    (content: Tags) => `/search/${content.tag_name}`
  );
  return { paths, fallback: false };
};

export const getStaticProps = async (
  context: GetStaticPropsContext<{ tag_name: string }>
) => {
  const tag_name = context.params?.tag_name;

  const data: Contents = await client.get({
    endpoint: "blog",
  });

  return {
    props: {
      blogs: {
        data,
        tag_name,
      },
    },
  };
};

const Home: NextPage<Props> = ({ blogs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{blogs.tag_name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {blogs.data.contents.map((blog: Blog) => {
          return (
            <p>{blog.body}</p>
            // <Card
            //   id={blog.id}
            //   thumbnail={b}
            //   title={blog.title}
            //   body={blog.body}
            //   key={blog.id}
            // />
          );
        })}
      </main>
    </div>
  );
};

export default Home;
