import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Card from "../components/Card";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Watataku's ブログ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <Card
          thumbnail={"kkkkkkkkkkkkkkkkk"}
          title={"タイトルです"}
          body={
            "詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。"
          }
        />
        <Card
          thumbnail={"kkkkkkkkkkkkkkkkk"}
          title={"タイトルです"}
          body={
            "詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。"
          }
        />
        <Card
          thumbnail={"kkkkkkkkkkkkkkkkk"}
          title={"タイトルです"}
          body={
            "詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。"
          }
        />
        <Card
          thumbnail={"kkkkkkkkkkkkkkkkk"}
          title={"タイトルです"}
          body={
            "詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。"
          }
        />
        <Card
          thumbnail={"kkkkkkkkkkkkkkkkk"}
          title={"タイトルです"}
          body={
            "詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。"
          }
        />
        <Card
          thumbnail={"kkkkkkkkkkkkkkkkk"}
          title={"タイトルです"}
          body={
            "詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。詳細です。"
          }
        />
      </main>

      <Footer />
    </div>
  );
};

export default Home;
