import { client } from "../seacretDirectory/seacret";

import type { InferGetStaticPropsType, NextPage } from "next";
import type { Contents, Blog } from "../types/blog";

import styles from "../styles/Home.module.css";
import Head from "next/head";
import Card from "../components/Card";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export const getStaticProps = async () => {
  const data: Contents = await client.get({ endpoint: "blog" });

  return {
    props: {
      blogs: data.contents,
    },
  };
};

const Home: NextPage<Props> = ({ blogs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Watataku's ブログ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {blogs.map((blog: Blog) => {
          return (
            <Card
              id={blog.id}
              thumbnail={blog.thumbnail.url}
              title={blog.title}
              body={blog.body}
              key={blog.id}
            />
          );
        })}
      </main>
    </div>
  );
};

export default Home;
