import type { GetStaticProps, NextPage } from "next";
import type { Contents, Blog } from "../types/blog";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Card from "../components/Card";
import Footer from "../components/Footer";
import { client } from "../seacretDirectory/seacret";

export const getStaticProps: GetStaticProps = async () => {
  const data: Contents = await client.get({ endpoint: "blog" });

  return {
    props: {
      blogs: data.contents,
    },
  };
};

const Home = ({ blogs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Watataku's ブログ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        {blogs.map((blog: Blog) => {
          return (
            <Card
              id={blog.id}
              thumbnail={blog.thumbnail.url}
              title={blog.title}
              body={blog.body}
              key={blog.id}
            />
          );
        })}
      </main>

      <Footer />
    </div>
  );
};

export default Home;
